// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 01 Sep 2026 15:07:50 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package gmk provides the raw cgo bindings for GNU Make loading dynamic objects
*/
package gmk
