// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 01 Sep 2026 15:07:50 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gmk

/*
#include <gnumake.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// Free function as declared in gnumake-go/gnumake.h:42
func Free(str []byte) {
	cstr, cstrAllocMap := (*C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&str)).Data)), cgoAllocsUnknown
	C.gmk_free(cstr)
	runtime.KeepAlive(cstrAllocMap)
}

// Alloc function as declared in gnumake-go/gnumake.h:45
func Alloc(len uint32) *byte {
	clen, clenAllocMap := (C.uint)(len), cgoAllocsUnknown
	__ret := C.gmk_alloc(clen)
	runtime.KeepAlive(clenAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// Expand function as declared in gnumake-go/gnumake.h:52
func Expand(str string) *byte {
	cstr, cstrAllocMap := unpackPCharString(str)
	__ret := C.gmk_expand(cstr)
	runtime.KeepAlive(cstrAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}
