// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 01 Sep 2026 15:07:50 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package gmk

/*
#include <gnumake.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// FileLocation as declared in gnumake-go/gnumake.h:27
type FileLocation struct {
	FileName       []byte
	LineNumber     uint64
	refe443217c    *C.gmk_floc
	allocse443217c interface{}
}
