// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 01 Sep 2026 15:36:41 CDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package gnumake provides the raw cgo bindings generated from gnumake.h
*/
package gnumake
